const continentCountry = {
  Asia: [
    "Japan",
    "Saudi Arabia",
    "China",
    "Korea South",
    "Taiwan",
    "Hong Kong",
    "Kuwait",
    "Malaysia",
    "Singapore",
    "Indonesia",
    "Thailand",
    "United Arab Emirates",
    "Qatar",
    "India",
    "Philippines",
    "Oman",
    "Iran",
    "Pakistan",
    "Syria",
    "Bahrain",
    "Uzbekistan",
    "Yemen",
    "Bangladesh",
    "Israel",
    "Jordan",
    "Turkmenistan",
    "Papua New Guinea",
    "Kazakhstan",
    "Tajikistan",
    "Laos",
    "Kyrgyzstan",
    "Burma",
    "Armenia",
    "Cambodia",
    "Iraq",
    "Sri Lanka",
    "Georgia",
    "Vietnam",
    "Lebanon",
    "Azerbaijan",
    "Turkey"
  ],
  "North America": [
    "Canada",
    "Haiti",
    "Cuba",
    "Panama",
    "Jamaica",
    "El Salvador",
    "Costa Rica",
    "Guatemala",
    "United States",
    "Belize"
  ],
  "South America": [
    "Venezuela",
    "Brazil",
    "Argentina",
    "Chile",
    "Trinidad and Tobago",
    "Dominican Republic",
    "Bolivia",
    "Ecuador",
    "Honduras",
    "Peru",
    "Paraguay",
    "Guyana",
    "Nicaragua",
    "Colombia",
    "Mexico",
    "Uruguay"
  ],
  Europe: [
    "Germany",
    "Russia",
    "Switzerland",
    "Norway",
    "Sweden",
    "Netherlands",
    "Belgium",
    "Finland",
    "Denmark",
    "Ukraine",
    "Bulgaria",
    "Slovenia",
    "Moldova",
    "Malta",
    "France",
    "Macedonia",
    "Albania",
    "Iceland",
    "Cyprus",
    "Belarus",
    "Estonia",
    "Latvia",
    "Slovakia",
    "Lithuania",
    "Croatia",
    "Bosnia and Herzegovina",
    "Ireland",
    "Serbia and Montenegro",
    "Austria",
    "Romania",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Greece",
    "Portugal",
    "Italy",
    "Spain",
    "United Kingdom"
  ],
  Africa: [
    "Algeria",
    "Libya",
    "Nigeria",
    "Egypt",
    "Morocco",
    "Botswana",
    "Chad",
    "Mauritius",
    "Congo Republic of the",
    "Namibia",
    "Gabon",
    "Ghana",
    "Tunisia",
    "Gambia The",
    "Sao Tome and Principe",
    "Angola",
    "Malawi",
    "Burundi",
    "Swaziland",
    "Cape Verde",
    "Seychelles",
    "Mozambique",
    "Lesotho",
    "Togo",
    "Eritrea",
    "Cameroon",
    "Benin",
    "Zambia",
    "Rwanda",
    "Zimbabwe",
    "Madagascar",
    "Guinea",
    "Tanzania",
    "Cote d'Ivoire",
    "Kenya",
    "Ethiopia",
    "Burkina Faso",
    "Senegal",
    "Equatorial Guinea",
    "Uganda",
    "Sudan",
    "South Africa"
  ],
  Oceania: ["New Zealand", "Australia"]
};

const higherTheMoreBetterOrDeveloped = [
  "Area",
  "Birth rate",
  "Current account balance",
  "Electricity consumption",
  "Electricity production",
  "Exports",
  "GDP",
  "GDP per capita",
  "GDP real growth rate",
  "Highways",
  "Imports",
  "Industrial production growth rate",
  "Internet users",
  "Investment",
  "Labor force",
  "Life expectancy at birth",
  "Military expenditures",
  "Natural gas consumption",
  "Oil consumption",
  "Population",
  "Railways",
  "Reserves of foreign exchange & gold",
  "Total fertility rate"
];
const higherTheWorseOrUndeveloped = [
  "Death rate",
  "Infant mortality rate",
  "Inflation rate",
  "Public debt",
  "Unemployment rate"
];
